config/routes.rb
Rails.application.routes.draw do
  # WEB上でメールを確認できる。必要なときのみコメントアウトを外す。
  # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env == 'development'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    # このpathを通して外部API認証が行われる。
    :omniauth_callbacks => 'users/omniauth_callbacks'
   }
  root 'homes#top'
  get '/about' => 'homes#about'
  # ジャンルごとの投稿一覧
  get '/posts/genre/:user_id/:id' => 'posts#genre_posts_index', as: 'genre_posts_index'
  # 復習完了した投稿一覧、ユーザーの区別をするためid有りにする
  get '/posts/completes/:user_id' => 'completes#index', as: 'complete_posts'
  # 復習回数が4回未満で復習完了する場合
  patch 'posts/:id/relearn_complete' => 'completes#relearn_complete', as: 'relearn_complete'
  # 全体ポイントランキング表示
  get '/point_rank' => 'ranks#point_rank'
  # 友達ポイントランキング表示
  get '/friend_point_rank' => 'ranks#friend_point_rank'
  # 全体の復習リズムランキング
  get '/rhythm_rank' => 'ranks#rhythm_rank'
  # 友達の復習リズムランキング
  get '/friend_rhythm_rank' => 'ranks#friend_rhythm_rank'
  # 退会確認画面
  get '/sign_out_confirm' => 'users#sign_out_confirmation'
  # 友達検索の画面
  get 'user/:id/friend_search' => 'friends#search', as: "friend_search"
  # 友達リクエスト一覧表示
  get 'user/:id/friend_receive' => 'friends#receive', as: "friend_receive"
  # リクエスト送ったときに使う
  post 'user/:id/send_request' => 'friends#send_request', as: "send_request"
  # リクエスト取り消し
  delete 'user/:id/cancel_request' => 'friends#cancel_request', as: "cancel_request"
  # 通知を全削除
  delete 'user/:id/notification' => 'notifications#destroy_all', as: "destroy_all_notifications"
  resources :users, only: [:edit, :update, :destroy] do
    resources :genres, only: [:index, :create, :update, :destroy]
    resources :notifications, only: [:index]
    resources :friends, only: [:index, :update, :destroy]
    # current_userと友達の投稿を区別する必要があるためネストする
    resources :posts do
      # 通知時間はpost_idが必要
      # plan_timingのidは不要のためresourceを使用
      resource :plan_timing, only: [:edit, :update]
      resource :complete, only: [:show, :update, :destroy]
      # 復習ポイントフォームでの入力値受け取り用
      resource :relearn_point, only: [:update]
    end
  end
end

app/models/friend.rb
class Friend < ApplicationRecord
  # リレーションシップに対応したidに対してbelongs_toの関連付けを追加する
  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'

  # バリデーション
  validates :sender_id, presence: true, numericality: { only_integer: true }
  validates :recipient_id, presence: true, numericality: { only_integer: true }
  validates :active_status, inclusion: { in: [true, false] }
  validates :send_request, inclusion: { in: [true, false] }

  # すでにフレンドになっているか確認するメソッド
  def self.friend_user?(current_user, friend_user)
    friend = Friend.where(active_status: true).where('(sender_id=?) or (recipient_id=?)',
                                                     current_user.id, current_user.id).where('(sender_id=?) or (recipient_id=?)', friend_user.id, friend_user.id)
    # friendの中身が空じゃないかつ友達になっているならtrueを返す
    friend[0].present? && friend[0].active_status
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  # ログインユーザーのみ実行可能にする
  before_action :authenticate_user!

  # 友達検索
  def search
    # userモデルにsearchメソッドを記述
    @users = User.search(params[:search_word], current_user.id).page(params[:page])
  end

  # 友達リクエストの送信
  def send_request
    # リクエストを送った時点でレコードを作成
    Friend.create(send_request: true, sender_id: current_user.id, recipient_id: params[:user_id], active_status: false)
    # リクエスト送信時の通知レコード作成メソッド
    User.create_notification_request!(current_user, params[:user_id])
    # each文中から引っ張ってきているので再定義必要
    @user_id = params[:user_id]
    render 'status_change'
  end

  # 友達リクエストの取り消し
  def cancel_request
    friend = Friend.find_by(send_request: true, sender_id: current_user.id, recipient_id: params[:user_id])
    friend.destroy
    # each文中から引っ張ってきているので再定義必要
    @user_id = params[:user_id]
    render 'status_change'
  end

  # 受け取った友達リクエスト一覧表示
  # リクエストを使うと'has_content_type?'とエラーが出る
  def receive
    @senders = Friend.where(recipient_id: current_user.id, send_request: true, active_status: false)
  end

  # 友達一覧
  def index
    # active_statusがtrueかつsender_idもしくはrecipient_idがcurrent_idの時の集合
    # whereで複数条件検索
    @friends = Friend.where(active_status: true).where('(sender_id=?) or (recipient_id=?)', current_user.id, current_user.id).page(params[:page])
  end

  # 友達リクエスト承認or拒否
  def update
    friend = Friend.find_by(sender_id: params[:id], recipient_id: current_user.id, send_request: true, active_status: false)
    # judgeにはtrueかfalseが入る
    if params[:judge] == 'true'
      if friend.update(active_status: true)
        # リクエスト承認したときの通知レコードを作成するメソッド
        User.create_notification_approve!(current_user, params[:id])
        flash[:warning] = 'リクエストを承認しました'
      else
        flash[:danger] = 'リクエストの承認に失敗しました'
      end
    else
      flash[:danger] = if friend.destroy
                         'リクエストを拒否しました'
                       else
                         'リクエストの拒否に失敗しました'
                       end
    end
    redirect_to request.referer
  end

  # 友達解除
  def destroy
    friend = Friend.where(active_status: true).where('(sender_id=?) or (recipient_id=?)',
                                                     current_user.id, current_user.id).where('(sender_id=?) or (recipient_id=?)', params[:id], params[:id])
    if friend[0].destroy
      flash[:warning] = '友達解除しました'
    else
      flash[:danger] = '友達解除に失敗しました'
    end
    redirect_to request.referer
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
  # リクエストの送受信状況の確認メソッド
  def send_request(user_id)
    # 自分がリクエストを送っている場合に値を持つ
    sender = Friend.where(sender_id: current_user.id, recipient_id: user_id, send_request: true)
    # 自分がリクエストが受け取っている場合に値を持つ
    recipient = Friend.where(sender_id: user_id, recipient_id: current_user.id, send_request: true)
    if sender.empty? && recipient.empty?
      0 # 0は未送信かつ未受信とする
    elsif sender.empty? && recipient.present? && recipient[0].active_status == false
      1 # 1は未送信かつ受信済とする
    elsif sender.present? && recipient.empty? && sender[0].active_status == false
      2 # 2はリクエスト送信済
    else
      3 # 3は自分or相手がリクエスト送信後承認済み
    end
  end
end

app/views/friends/_friend.html.erb
<table class="friend_table">
  <thead class="friend_thead">
    <th></th>
    <th><p>友達：<%= models.length %>人</p></th>
  </thead>
  <tbody class="friend_tbody">
    <%# modelsはレンダリング元から渡している各モデルを参照している %>
    <% models.each do |model| %>
      <% if model.sender.id == current_user.id %>
        <tr>
          <td><p><%= attachment_image_tag(model.recipient, :image, :fill, 50, 50, fallback: "default.png", class: "friend_image") %></p></td>
          <td><p><%= model.recipient.name %></p></td>
          <td><%= link_to user_posts_path(user_id: model.recipient_id) do %><p class="friend_index_posts_btn">友達の投稿</p><% end %></td>
          <td><%= link_to user_friend_path(user_id: current_user.id, id: model.recipient_id),method: :delete, data: {confirm: "本当に解除しますか？"} do %><p class="friend_request_reject_btn">友達解除</p><% end %></td>
        </tr>
      <% else %>
        <tr>
          <td><p><%= attachment_image_tag(model.sender, :image, :fill, 50, 50, fallback: "default.png", class: "friend_image") %></p></td>
          <td><p><%= model.sender.name %></p></td>
          <td><%= link_to user_posts_path(user_id: model.sender_id) do %><p class="friend_index_posts_btn">友達の投稿</p><% end %></td>
          <td><%= link_to user_friend_path(user_id: current_user.id, id: model.sender_id),method: :delete, data: {confirm: "本当に解除しますか？"} do %><p class="friend_request_reject_btn">友達解除</p><% end %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<%= paginate @friends %>

app/views/friends/_receive.html.erb
<table class="receive_table">
  <thead class="receive_thead">
    <th></th>
    <th><p>リクエスト数：<%= models.length %>件</p></th>
  </thead>
  <tbody class="receive_tbody">
    <%# modelsはレンダリング元から渡している各モデルを参照している %>
    <% models.each do |model| %>
      <tr>
        <td><p><%= attachment_image_tag(model.sender, :image, :fill, 50, 50, fallback: "default.png", class: "friend_image") %></p></td>
        <td><p><%= model.sender.name %></p></td>
        <td><%= link_to user_friend_path(user_id: current_user.id, id: model.sender_id, judge: true),method: :patch do %><p class="friend_request_approve_btn">承認</p><% end %></td>
        <td><%= link_to user_friend_path(user_id: current_user.id, id: model.sender_id, judge: false),method: :patch do %><p class="friend_request_reject_btn">拒否</p><% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/friends/_request_status.html.erb
<%# リクエスト送信済みか判断する条件分岐 %>
<% if send_request(user_id) == 0 %>
  <%# リクエスト未送信かつ未受信 %>
  <%= link_to send_request_path(id: current_user.id, user_id: user_id),method: :post, remote: true do %>
    <div class="friend_request_btn"><p>友達リクエスト</p></div><% end %>
<% elsif send_request(user_id) == 1 %>
  <%# リクエスト未送信かつ受信済 %>
  <%= link_to friend_receive_path(current_user.id) do %><div class="friend_request_receive_btn"><p>リクエスト未承認</p></div><% end %>
<% elsif send_request(user_id) == 2 %>
  <%# リクエスト送信済かつ承認済 %>
  <%= link_to cancel_request_path(id: current_user.id, user_id: user_id),method: :delete, remote: true do %>
    <div class="friend_request_reject_btn"><p>取り消し</p></div><% end %>
<% else %>
  <%# リクエスト送信済かつ未承認 %>
  <%= link_to user_friends_path(current_user.id) do %><div class="already_friend_btn"><p>友達</p></div><% end %>
<% end %>

app/views/friends/_search.html.erb
<table class="search_table">
  <thead class="search_thead">
    <th></th>
    <th><p>検索結果：<%= models.length %>件</p></th>
  </thead>
  <tbody class="search_tbody">
    <%# modelsはレンダリング元から渡している各モデルを参照している %>
    <% models.each do |model| %>
      <tr>
        <td><p><%= attachment_image_tag(model, :image, :fill, 50, 50, fallback: "default.png", class: "friend_image") %></p></td>
        <td><p><%= model.name %></p></td>
        <td></td>
        <td><%= link_to user_posts_path(user_id: model.id) do %><p class="friend_index_posts_btn">投稿を見る</p><% end %></td>
        <td><p><div id="request_render_<%= model.id %>">
                  <%= render partial: "friends/request_status", locals: { user_id: model.id} %>
                </div></p></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @users %>

app/views/friends/index.html.erb
<%# 友達一覧ビュー %>
<h1>友達を探そう</h1>
<div class="friend_custom">
  <%# 全体か友達（自分含む）かを選べるタブ %>
  <div class="friend_custom_bar">
    <%= link_to "友達検索", friend_search_path(current_user.id), class:"friend_tab" %>
    <%= link_to "リクエスト承認待ち", friend_receive_path(current_user.id), class:"friend_tab" %>
    <%= link_to "友達一覧", user_friends_path(current_user.id), class:"friend_index_tab" %>
  </div>
  <%# 友達の一覧、検索結果も含めて %>
  <div class="friend_box">
    <%# 友達一覧を表示 %>
    <%= render partial: "friends/friend", locals: { models: @friends } %>
  </div>
</div>

app/views/friends/receive.html.erb
<%# 友達検索ビュー %>
<h1>友達を探そう</h1>
<div class="friend_custom">
  <%# 全体か友達（自分含む）かを選べるタブ %>
  <div class="friend_custom_bar">
    <%= link_to "友達検索", friend_search_path(current_user.id), class:"friend_tab" %>
    <%= link_to "リクエスト承認待ち", friend_receive_path(current_user.id), class:"friend_receive_tab" %>
    <%= link_to "友達一覧", user_friends_path(current_user.id), class:"friend_tab" %>
  </div>
  <%# 友達の一覧、検索結果も含めて %>
  <div class="friend_main_box">
    <%# リクエスト一覧を表示 %>
    <%= render partial: "friends/receive", locals: { models: @senders } %>
  </div>
</div>

app/views/friends/search.html.erb
<%# 友達検索ビュー %>
<h1>友達を探そう</h1>
<div class="friend_custom">
  <%# 全体か友達（自分含む）かを選べるタブ %>
  <div class="friend_custom_bar">
    <%= link_to "友達検索", friend_search_path(current_user.id), class:"friend_search_tab" %>
    <%= link_to "リクエスト承認待ち", friend_receive_path(current_user.id), class:"friend_tab" %>
    <%= link_to "友達一覧", user_friends_path(current_user.id), class:"friend_tab" %>
  </div>
  <div class="friend_top_box">
    <p>友達の名前を入れてみよう</p>
    <div class="friend_search_form">
      <%# 検索はDBの変更にかかわらないのでform_tagを使うほうが使い勝手が良い %>
      <%# remote:trueで非同期検索 %>
      <%= form_tag(friend_search_path, method: :get, remote: true) do %>
        <%# 名前だけで検索する %>
        <%= text_field_tag :search_word, "" , { class: "search_form" } %>
        <%= submit_tag '検索', class: "search_submit" %>
      <% end %>
    </div>
  </div>
  <%# 友達の一覧、検索結果も含めて %>
  <div class="friend_main_box">
    <div id="search_ajax">
      <%# 検索結果を一覧表示 %>
      <%= render partial: "friends/search", locals: { models: @users } %>
    </div>
  </div>
</div>

app/views/friends/search.js.erb
$('#search_ajax').html("<%= j(render partial: 'friends/search', locals: {models: @users}) %>");

app/views/friends/status_change.js.erb
<%# 指定した部分のHTMLだけ、renderで部分的に更新するという処理 %>
$('#request_render_<%= @user_id %>').html("<%= j(render partial: 'friends/request_status', locals: {user_id: @user_id}) %>");