config/routes.rb
Rails.application.routes.draw do
  # WEB上でメールを確認できる。必要なときのみコメントアウトを外す。
  # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env == 'development'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    # このpathを通して外部API認証が行われる。
    :omniauth_callbacks => 'users/omniauth_callbacks'
   }
  root 'homes#top'
  get '/about' => 'homes#about'
  # ジャンルごとの投稿一覧
  get '/posts/genre/:user_id/:id' => 'posts#genre_posts_index', as: 'genre_posts_index'
  # 復習完了した投稿一覧、ユーザーの区別をするためid有りにする
  get '/posts/completes/:user_id' => 'completes#index', as: 'complete_posts'
  # 復習回数が4回未満で復習完了する場合
  patch 'posts/:id/relearn_complete' => 'completes#relearn_complete', as: 'relearn_complete'
  # 全体ポイントランキング表示
  get '/point_rank' => 'ranks#point_rank'
  # 友達ポイントランキング表示
  get '/friend_point_rank' => 'ranks#friend_point_rank'
  # 全体の復習リズムランキング
  get '/rhythm_rank' => 'ranks#rhythm_rank'
  # 友達の復習リズムランキング
  get '/friend_rhythm_rank' => 'ranks#friend_rhythm_rank'
  # 退会確認画面
  get '/sign_out_confirm' => 'users#sign_out_confirmation'
  # 友達検索の画面
  get 'user/:id/friend_search' => 'friends#search', as: "friend_search"
  # 友達リクエスト一覧表示
  get 'user/:id/friend_receive' => 'friends#receive', as: "friend_receive"
  # リクエスト送ったときに使う
  post 'user/:id/send_request' => 'friends#send_request', as: "send_request"
  # リクエスト取り消し
  delete 'user/:id/cancel_request' => 'friends#cancel_request', as: "cancel_request"
  # 通知を全削除
  delete 'user/:id/notification' => 'notifications#destroy_all', as: "destroy_all_notifications"
  resources :users, only: [:edit, :update, :destroy] do
    resources :genres, only: [:index, :create, :update, :destroy]
    resources :notifications, only: [:index]
    resources :friends, only: [:index, :update, :destroy]
    # current_userと友達の投稿を区別する必要があるためネストする
    resources :posts do
      # 通知時間はpost_idが必要
      # plan_timingのidは不要のためresourceを使用
      resource :plan_timing, only: [:edit, :update]
      resource :complete, only: [:show, :update, :destroy]
      # 復習ポイントフォームでの入力値受け取り用
      resource :relearn_point, only: [:update]
    end
  end
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
  # ログインユーザーのみ実行可能にする
  before_action :authenticate_user!

  # 全体ポイントランキングの表示
  def point_rank
    @exclude_users = User.where(rank_status: false)
    # 合計ポイントが0ではなく、降順に並べる
    @total_points = TotalPoint.where.not(score: 0).order(score: :desc)
    # ランキング掲載したくない人は除くメソッド
    @point_ranks = TotalPoint.exclude(@exclude_users, @total_points)
  end

  # 友達ポイントランキングの表示
  def friend_point_rank
    # 友達になったらランキング掲載不可関係なく表示する
    # 自分が送信か受信したリクエストが承認されていれば友達の集合ができる
    @friends = Friend.where(active_status: true).where('sender_id=? or recipient_id=?', current_user.id, current_user.id)
    # 友達のidを使ってスコアの高い順番に分けるメソッド
    @friend_point_ranks = TotalPoint.sorting(@friends, current_user.id)
  end

  # 全体リズムランキングの表示
  def rhythm_rank
    @exclude_users = User.where(rank_status: false)
    @rates = Rate.where.not(count: 0).order(total_rate: :desc)
    # ランキングに掲載したくない人は除くメソッド
    @rhythm_ranks = Rate.exclude(@exclude_users, @rates)
  end

  # 友達ポイントランキングの表示
  def friend_rhythm_rank
    # 友達になったらランキング掲載不可関係なく表示する
    # 自分が送信か受信したリクエストが承認されていれば友達の集合ができる
    @friends = Friend.where(active_status: true).where('sender_id=? or recipient_id=?', current_user.id, current_user.id)
    # 友達のidを使って平均復習率の高い順番に分けるメソッド
    @friend_rhythm_ranks = Rate.sorting(@friends, current_user.id)
  end
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/views/ranks/_point_rank.html.erb
<%# 合計ポイントのランキング %>
<table class="rank_table">
  <thead class="rank_thead">
    <tr>
      <td><p>順位</p></td>
      <td></td>
      <td><p>ユーザー名</p></td>
      <td><p>Relearnポイント</p></td>
    </tr>
  </thead>
  <tbody class="rank_tbody">
    <%# modelsはレンダリング元から渡している各モデルを参照している %>
    <% models.each.with_index(1) do |model, i| %>
      <tr>
        <td><p><%= i %>位</p></td>
        <td><p><%= attachment_image_tag(model.user, :image, :fill, 50, 50, fallback: "default.png", class: "rank_user_image") %></p></td>
        <td><p><%= model.user[:name] %></p></td>
        <td><p><%= model[:score] %>P</p></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/ranks/_rhythm_rank.html.erb
<%# 復習リズムランキングのテーブル %>
<table class="rank_table">
  <thead class="rank_thead">
    <tr>
      <td><p>順位</p></td>
      <td></td>
      <td><p>ユーザー名</p></td>
      <td><p>復習リズム</p></td>
    </tr>
  </thead>
  <tbody class="rank_tbody">
    <%# modelsはレンダリング元から渡している各モデルを参照している %>
    <% models.each.with_index(1) do |model, i| %>
      <% user = User.find(model[:user_id]) %>
      <tr>
        <td><p><%= i %>位</p></td>
        <td><p><%= attachment_image_tag(user, :image, :fill, 50, 50, fallback: "default.png", class: "rank_user_image") %></p></td>
        <td><p><%= user[:name] %></p></td>
        <td><p><%= sprintf("%.2f", model[:average_rate]) %></p></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/ranks/friend_point_rank.html.erb
<h1>ランキング</h1>
<div class="rank_custom">
  <%# 全体か友達（自分含む）かを選べるタブ %>
  <div class="rank_custom_bar">
    <%= link_to "全体", point_rank_path, class:"rank_item" %>
    <%= link_to "友達", friend_point_rank_path, class:"friend_rank_tab" %>
  </div>
  <%# ポイントかリズムのランキングを選べるリンク %>
  <div class="rank_custom_bar">
    <%= link_to "Relearnポイント", point_rank_path, class:"point_rank_tab" %>
    <%= link_to "復習リズム", friend_rhythm_rank_path, class:"rank_item" %>
  </div>

  <%# 友達の獲得ポイントランキング %>
  <div class="friend_point_rank_box">
    <% if @friend_point_ranks.blank? %>
      <br><p>まだデータがありません</p>
    <% else %>
      <%# テーブルでランキング表示 %>
      <%= render partial: "ranks/point_rank", locals: { models: @friend_point_ranks} %>
    <% end %>
  </div>
</div>

app/views/ranks/friend_rhythm_rank.html.erb
<h1>ランキング</h1>
<div class="rank_custom">
  <%# 全体か友達（自分含む）かを選べるタブ %>
  <div class="rank_custom_bar">
    <%= link_to "全体", rhythm_rank_path, class:"rank_item" %>
    <%= link_to "友達", friend_rhythm_rank_path, class:"friend_rank_tab" %>
  </div>
  <%# ポイントかリズムのランキングを選べるリンク %>
  <div class="rank_custom_bar">
    <%= link_to "Relearnポイント", friend_point_rank_path, class:"rank_item" %>
    <%= link_to "復習リズム", friend_rhythm_rank_path, class:"rhythm_rank_tab" %>
  </div>

  <%# 友達の復習リズムランキング %>
  <div class="friend_rhythm_rank_box">
    <% if @friend_rhythm_ranks.blank? %>
      <br><p>まだデータがありません</p>
    <% else %>
      <%# テーブルでランキング表示 %>
      <%= render partial: "ranks/rhythm_rank", locals: { models: @friend_rhythm_ranks} %>
    <% end %>
  </div>
</div>

app/views/ranks/point_rank.html.erb
<h1>ランキング</h1>
<div class="rank_custom">
  <%# 全体か友達（自分含む）かを選べるタブ %>
  <div class="rank_custom_bar">
    <%= link_to "全体", point_rank_path, class:"all_rank_tab" %>
    <%= link_to "友達", friend_point_rank_path, class:"rank_item" %>
  </div>
  <%# ポイントかリズムのランキングを選べるリンク %>
  <div class="rank_custom_bar">
    <%= link_to "Relearnポイント", point_rank_path, class:"point_rank_tab" %>
    <%= link_to "復習リズム", rhythm_rank_path, class:"rank_item" %>
  </div>

  <%# 全体の獲得ポイントランキング %>
  <div class="all_point_rank_box">
    <% if @point_ranks.blank? %>
      <br><p>まだデータがありません</p>
    <% else %>
      <%# テーブルでランキング表示 %>
      <%= render partial: "ranks/point_rank", locals: { models: @point_ranks} %>
    <% end %>
  </div>
</div>

app/views/ranks/rhythm_rank.html.erb
<h1>ランキング</h1>
<div class="rank_custom">
  <%# 全体か友達（自分含む）かを選べるタブ %>
  <div class="rank_custom_bar">
    <%= link_to "全体", rhythm_rank_path, class:"all_rank_tab" %>
    <%= link_to "友達", friend_rhythm_rank_path, class:"rank_item" %>
  </div>
  <%# ポイントかリズムのランキングを選べるリンク %>
  <div class="rank_custom_bar">
    <%= link_to "Relearnポイント", point_rank_path, class:"rank_item" %>
    <%= link_to "復習リズム", rhythm_rank_path, class:"rhythm_rank_tab" %>
  </div>

  <%# 全体の復習リズムランキング %>
  <div class="all_rhythm_rank_box">
    <% if @rhythm_ranks.blank? %>
      <br><p>まだデータがありません</p>
    <% else %>
      <%# テーブルでランキング表示 %>
      <%= render partial: "ranks/rhythm_rank", locals: { models: @rhythm_ranks} %>
    <% end %>
  </div>
</div>