config/routes.rb
Rails.application.routes.draw do
  # WEB上でメールを確認できる。必要なときのみコメントアウトを外す。
  # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env == 'development'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    # このpathを通して外部API認証が行われる。
    :omniauth_callbacks => 'users/omniauth_callbacks'
   }
  root 'homes#top'
  get '/about' => 'homes#about'
  # ジャンルごとの投稿一覧
  get '/posts/genre/:user_id/:id' => 'posts#genre_posts_index', as: 'genre_posts_index'
  # 復習完了した投稿一覧、ユーザーの区別をするためid有りにする
  get '/posts/completes/:user_id' => 'completes#index', as: 'complete_posts'
  # 復習回数が4回未満で復習完了する場合
  patch 'posts/:id/relearn_complete' => 'completes#relearn_complete', as: 'relearn_complete'
  # 全体ポイントランキング表示
  get '/point_rank' => 'ranks#point_rank'
  # 友達ポイントランキング表示
  get '/friend_point_rank' => 'ranks#friend_point_rank'
  # 全体の復習リズムランキング
  get '/rhythm_rank' => 'ranks#rhythm_rank'
  # 友達の復習リズムランキング
  get '/friend_rhythm_rank' => 'ranks#friend_rhythm_rank'
  # 退会確認画面
  get '/sign_out_confirm' => 'users#sign_out_confirmation'
  # 友達検索の画面
  get 'user/:id/friend_search' => 'friends#search', as: "friend_search"
  # 友達リクエスト一覧表示
  get 'user/:id/friend_receive' => 'friends#receive', as: "friend_receive"
  # リクエスト送ったときに使う
  post 'user/:id/send_request' => 'friends#send_request', as: "send_request"
  # リクエスト取り消し
  delete 'user/:id/cancel_request' => 'friends#cancel_request', as: "cancel_request"
  # 通知を全削除
  delete 'user/:id/notification' => 'notifications#destroy_all', as: "destroy_all_notifications"
  resources :users, only: [:edit, :update, :destroy] do
    resources :genres, only: [:index, :create, :update, :destroy]
    resources :notifications, only: [:index]
    resources :friends, only: [:index, :update, :destroy]
    # current_userと友達の投稿を区別する必要があるためネストする
    resources :posts do
      # 通知時間はpost_idが必要
      # plan_timingのidは不要のためresourceを使用
      resource :plan_timing, only: [:edit, :update]
      resource :complete, only: [:show, :update, :destroy]
      # 復習ポイントフォームでの入力値受け取り用
      resource :relearn_point, only: [:update]
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # ログインユーザーのみ実行可能にする
  before_action :authenticate_user!
  # 自分と友達以外の投稿情報は見れないようにチェック
  before_action :searchable_user_check, only: [:index, :genre_posts_index, :show, :new, :edit]

  # 投稿の新規登録
  def new
    @post = Post.new
  end

  # 投稿一覧画面の表示
  def index
    @posts = Post.where(user_id: params[:user_id], relearn_complete: false).page(params[:page])
    @genres = Genre.where(user_id: params[:user_id]).limit(20)
  end

  # ジャンルごとの投稿一覧
  def genre_posts_index
    @genre = Genre.find(params[:id])
    @posts = Post.where(user_id: params[:user_id], genre_id: @genre.id).page(params[:page])
    @genres = Genre.where(user_id: params[:user_id]).limit(20)
    # もし入力されたgenreのidが自分でも友達でもなければトップページへとばす
    return unless @genre.user.id != @other_user.id

    flash[:danger] = 'このユーザーの投稿は見れなくなっています。'
    redirect_to root_path
  end

  # 投稿詳細画面の表示
  def show
    @post = Post.find(params[:id])
    @genre = Genre.find_by(id: @post.genre_id)
    # _point_formで使用するrelearn_pointのデータの入れ方条件分岐
    if RelearnPoint.find_by(post_id: params[:id]).nil?
      # もしrelearn_pointのレコードがなければ作らせる
      RelearnPoint.create!(post_id: params[:id])
    end
    # 通知時間の表示用
    @plan_timing = Form::PlanTiming.find_by(post_id: params[:id])
    # 通知時間と現在時刻の差異でフォームの出すタイミングを設定
    @time_now = Time.zone.now
    @real_timing = RealTiming.find_by(post_id: params[:id])
  end

  # 新規投稿の保存
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      # 新規投稿時に復習ポイントのレコードと通知予定時間のレコードを作成する
      RelearnPoint.create!(post_id: @post.id)
      # 予定している通知時間を1日後、3日後、10日後、1ヶ月後に設定
      PlanTiming.create!(post_id: @post.id,
                         first_term: 1.day.from_now, second_term: 3.days.from_now,
                         third_term: 10.days.from_now, forth_term:  1.month.from_now,
                         first_min: 1.hour.from_now, first_max:   2.days.from_now,
                         second_min: 2.days.from_now, second_max:  7.days.from_now,
                         third_min: 7.days.from_now, third_max:  14.days.from_now,
                         forth_min: 14.days.from_now, forth_max:   1.month.from_now)
      RealTiming.create!(post_id: @post.id)
      flash[:warning] = '投稿完了しました。'
      redirect_to user_post_path(user_id: current_user.id, id: @post.id)
    else
      flash[:danger] = 'ジャンル、タイトル、内容は必須です。'
      render :new
    end
  end

  # 投稿の編集
  def edit
    @post = Post.find(params[:id])
  end

  # 編集内容の更新
  def update
    @post = Post.find(params[:id])
    @post.user_id = current_user.id
    if @post.update(post_params)
      flash[:warning] = '更新完了しました。'
      redirect_to user_post_path(user_id: current_user.id, id: @post.id)
    else
      flash[:danger] = 'ジャンル、タイトル、内容は必須です'
      render :edit
    end
  end

  # 投稿の削除
  def destroy
    post = Post.find(params[:id])
    if post.destroy
      flash[:warning] = '投稿削除しました。'
      redirect_to user_posts_path(user_id: current_user.id)
    else
      flash[:danger] = '投稿削除に失敗しました。'
      redirect_to request.referer
    end
  end

  private

  def post_params
    params.require(:post).permit(:genre_id, :title, :content, :link)
  end

  # 検索可能者または友達かを判断するメソッド
  def searchable_user_check
    @other_user = User.find(params[:user_id])
    # 利用ユーザーと入力されたユーザーのidが同じなら自分のビューを見ることになる
    return if current_user.id == params[:user_id].to_i
    return if @other_user.search_status
    return if Friend.friend_user?(current_user, @other_user)

    # 友達でないかつ検索負荷の人の場合はエラーメッセージと共にルートへ飛ばす
    flash[:danger] = 'このユーザーの投稿情報は見れないようになっています'
    redirect_to root_path
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  # グラフ化するために[時間,記憶率]の配列を返す
  def memory_point_array(post)
    post_time = post.created_at
    memory_array = []
    # 投稿時刻の1分前を記憶率0%として挿入
    memory_array.push([post_time.ago(1.minute), 0])
    # 投稿時刻を記憶率100%として挿入
    memory_array.push([post_time, 100])

    # 復習回数に応じて記憶低減率はゆるやかになるようにわける
    if post.relearn_count.zero?
      # diff_timeは作成時と現在の時間の差分(単位は秒)
      diff_time = Time.zone.now - post.created_at
      # 投稿から現在までの0回目の記憶節約率を計算して配列に入れるメソッド
      zero_count_memory(post_time, diff_time, memory_array)

    elsif post.relearn_count == 1
      # 復習1回するまでの時間を計算
      diff_first_time   = post.real_timings[0][:first_term] - post_time
      # 復習1回目から現在までの時間を計算
      diff_first_to_now = Time.zone.now - post.real_timings[0][:first_term]
      # 投稿から復習1回目までの0回目の記憶節約率使って計算して配列に入れるメソッド
      zero_count_memory(post_time, diff_first_time, memory_array)
      # 復習時に100%に戻る
      memory_array.push([post.real_timings[0][:first_term], 100])
      # 復習1回目から現在までの記憶節約率を計算して配列に入れるメソッド
      first_count_memory(post.real_timings[0][:first_term], diff_first_to_now, memory_array)

    elsif post.relearn_count == 2
      # 復習1回するまでの時間を計算
      diff_first_time      = post.real_timings[0][:first_term]  - post_time
      # 復習1回目から2回目までの時間を計算
      diff_first_to_second = post.real_timings[0][:second_term] - post.real_timings[0][:first_term]
      # 復習2回目から現在までの時間を計算
      diff_second_to_now   = Time.zone.now                      - post.real_timings[0][:second_term]
      # 投稿から復習1回目までの0回目の記憶節約率使って計算して配列に入れるメソッド
      zero_count_memory(post_time, diff_first_time, memory_array)
      # 復習時に100%に戻る
      memory_array.push([post.real_timings[0][:first_term], 100])
      # 復習1回目から2回目までの記憶節約率を計算して配列に入れるメソッド
      first_count_memory(post.real_timings[0][:first_term], diff_first_to_second, memory_array)
      # 復習時に100%に戻る
      memory_array.push([post.real_timings[0][:second_term], 100])
      # 復習2回目現在までの記憶節約率を計算して配列に入れるメソッド
      second_count_memory(post.real_timings[0][:second_term], diff_second_to_now, memory_array)
    elsif post.relearn_count == 3
      # 復習1回するまでの時間を計算
      diff_first_time      = post.real_timings[0][:first_term]  - post_time
      # 復習1回目から2回目までの時間を計算
      diff_first_to_second = post.real_timings[0][:second_term] - post.real_timings[0][:first_term]
      # 復習2回目から3回目までの時間を計算
      diff_second_to_third = post.real_timings[0][:third_term]  - post.real_timings[0][:second_term]
      # 復習3回目から現在までの時間を計算
      diff_third_to_now    = Time.zone.now                      - post.real_timings[0][:third_term]
      # 投稿から復習1回目までの0回目の記憶節約率使って計算して配列に入れるメソッド
      zero_count_memory(post_time, diff_first_time, memory_array)
      # 復習時に100%に戻る
      memory_array.push([post.real_timings[0][:first_term], 100])
      # 復習1回目から2回目までの記憶節約率を計算して配列に入れるメソッド
      first_count_memory(post.real_timings[0][:first_term], diff_first_to_second, memory_array)
      # 復習時に100%に戻る
      memory_array.push([post.real_timings[0][:second_term], 100])
      # 復習2回目から３回目までの記憶節約率を計算して配列に入れるメソッド
      second_count_memory(post.real_timings[0][:second_term], diff_second_to_third, memory_array)
      # 復習時に100%に戻る
      memory_array.push([post.real_timings[0][:third_term], 100])
      # 復習3回目現在までの記憶節約率を計算して配列に入れるメソッド
      third_count_memory(post.real_timings[0][:third_term], diff_third_to_now, memory_array)
    elsif post.relearn_count == 4
      # 復習1回するまでの時間を計算
      diff_first_time      = post.real_timings[0][:first_term]  - post_time
      # 復習1回目から2回目までの時間を計算
      diff_first_to_second = post.real_timings[0][:second_term] - post.real_timings[0][:first_term]
      # 復習2回目から3回目までの時間を計算
      diff_second_to_third = post.real_timings[0][:third_term]  - post.real_timings[0][:second_term]
      # 復習3回目から4回目までの時間を計算
      diff_third_to_forth  = post.real_timings[0][:forth_term]  - post.real_timings[0][:third_term]
      # 復習4回目から現在までの時間を計算
      diff_forth_to_now    = Time.zone.now - post.real_timings[0][:forth_term]
      # 投稿から復習1回目までの0回目の記憶節約率使って計算して配列に入れるメソッド
      zero_count_memory(post_time, diff_first_time, memory_array)
      # 復習時に100%に戻る
      memory_array.push([post.real_timings[0][:first_term], 100])
      # 復習1回目から2回目までの記憶節約率を計算して配列に入れるメソッド
      first_count_memory(post.real_timings[0][:first_term], diff_first_to_second, memory_array)
      # 復習時に100%に戻る
      memory_array.push([post.real_timings[0][:second_term], 100])
      # 復習2回目から３回目までの記憶節約率を計算して配列に入れるメソッド
      second_count_memory(post.real_timings[0][:second_term], diff_second_to_third, memory_array)
      # 復習時に100%に戻る
      memory_array.push([post.real_timings[0][:third_term], 100])
      # 復習3回目から４回目までの記憶節約率を計算して配列に入れるメソッド
      third_count_memory(post.real_timings[0][:third_term], diff_third_to_forth, memory_array)
      # 復習時に100%に戻る
      memory_array.push([post.real_timings[0][:forth_term], 100])
      # 復習4回目から現在までの記憶節約率を計算して配列に入れるメソッド
      forth_count_memory(post.real_timings[0][:forth_term], diff_forth_to_now, memory_array)
    # 例外処理
    else
      return
    end
    # 送る値は日付だけにする
    memory_array.map { |k, v| [k.strftime('%m/%d %H:%M'), v] }
  end

  def zero_count_memory(post_time, diff_time, memory_array)
    # 投稿から20分経っていた場合は42%記憶が落ちる
    # 1時間ごとに56％,1日後に74%,1週間後に77%,1ヶ月後に79%忘れる。
    # 第3引数は記憶の下降係数lost_rateとする
    # 第4引数は記憶のX軸に追加するadd_xとする
    # 第5引数は記憶のY軸に追加するadd_yとする
    # 頂点が点(1,44)で(20/60,58)を通るので、２次関数を計算するとy=31.5*(x-1)**2+44となる
    minute_lost_memory(post_time, diff_time, memory_array, 31.5, 1, 44) if diff_time > 300
    # 差分が1時間以上ある場合に実行
    # 頂点が(24,26)で点(1,44)を通るので、y=0.034(x-24)2+26 となる
    hour_lost_memory(post_time,   diff_time, memory_array, 0.034, 24, 26) if diff_time > 3600
    # 差分が1日以上ある場合に実行
    # 頂点が(31,21)で点(1,26)を通るので、２次関数を計算するとy=0.0055555*(x-31)**2+21となる
    day_lost_memory(post_time,    diff_time, memory_array, 0.0055555, 31, 21) if diff_time > 86_400
  end

  # 復習1回目現在までの記憶節約率を計算して配列に入れるメソッド
  def first_count_memory(post_time, diff_first, memory_array)
    # 差分が5分以上ある場合に実行
    # 頂点が(3,68)
    # 頂点が(1,76)で(1/3,82)を通るので、２次関数を計算するとy=13.5*(x-1)**2+76となる
    minute_lost_memory(post_time, diff_first, memory_array, 13.5, 1, 76) if diff_first > 300
    # 差分が1時間以上ある場合に実行
    # 頂点が(3,68)で点(1,100)を通るので、２次関数を計算するとy=0.014584*(x-24)**2+68.285となる
    hour_lost_memory(post_time, diff_first, memory_array, 0.014584, 24, 68.285) if diff_first > 3600
    # 差分が1日以上ある場合に実行
    # 頂点が(30,66.142)で点(1/24,76)を通るので、２次関数を計算するとy=0.01098*(x-31)**2+66.142となる
    day_lost_memory(post_time, diff_first, memory_array, 0.00238, 31, 66.142) if diff_first > 86_400
  end

  # 復習2回目現在までの記憶節約率を計算して配列に入れるメソッド
  def second_count_memory(post_time, diff_second, memory_array)
    # 差分が5分以上ある場合に実行
    # 頂点が(1,89.9366)で点(1/3,92.452)を通るので、２次関数を計算するとy=5.6597*(x-1)**2+89.9366となる
    minute_lost_memory(post_time, diff_second, memory_array, 5.6597, 1, 89.9366) if diff_second > 300
    # 差分が1時間以上ある場合に実行
    # 頂点が（24,86.7)で点(1,89.9366)を通るので、２次関数を計算するとy=0.006118*(x-24)**2+86.7となる
    hour_lost_memory(post_time, diff_second, memory_array, 0.006118, 24, 86.7) if diff_second > 3600
    # 差分が1日以上ある場合に実行
    # 頂点が(31,85.8)で点(1/24,89.9366)を通るので、２次関数を計算するとy=0.001*(x-31)**2+85.8となる
    day_lost_memory(post_time, diff_second, memory_array, 0.001, 31, 85.8) if diff_second > 86_400
  end

  # 復習3回目現在までの記憶節約率を計算して配列に入れるメソッド
  def third_count_memory(post_time, diff_third, memory_array)
    # 差分が5分以上ある場合に実行
    # 頂点が(1,95.1)で点(1/3,96.325)を通るので、２次関数を計算するとy=2.7563*(x-1)**2+95.1となる
    minute_lost_memory(post_time, diff_third, memory_array, 2.7563, 1, 95.1)    if diff_third > 300
    # 差分が1時間以上ある場合に実行
    # 頂点が(24,93.525)で点（1,95.1）を通るので、２次関数を計算するとy=0.002977*(x-20)**2+88となる
    hour_lost_memory(post_time, diff_third, memory_array, 0.002977, 24, 93.525) if diff_third > 3600
    # 差分が1日以上ある場合に実行
    # 頂点が(31,93.0866)で点(1/24,95.1)を通るので、２次関数を計算するとy=0.0004871*(x-31)**2+93.0866となる
    day_lost_memory(post_time, diff_third, memory_array, 0.0004871, 31, 93.0866) if diff_third > 86_400
  end

  def forth_count_memory(post_time, diff_forth, memory_array)
    # 差分が5分以上ある場合に実行
    # 頂点が(1,97.729)で点(1/3,98.297)を通るので、２次関数を計算するとy=1.278*(x-1)**2+97.729となる
    minute_lost_memory(post_time, diff_forth, memory_array, 1.278,      1, 97.729) if diff_forth > 300
    # 差分が1時間以上ある場合に実行
    # 頂点が(24,97)で点（1,97.729）を通るので、２次関数を計算するとy=0.001378*(x-24)**2+97となる
    hour_lost_memory(post_time, diff_forth, memory_array, 0.001378, 24, 97) if diff_forth > 3600
    # 差分が1日以上ある場合に実行
    # 頂点が(31,96.796)で点(1,97)を通るので、２次関数を計算するとy=0.00022666*(x-31)**2+96.796となる
    day_lost_memory(post_time, diff_forth, memory_array, 0.00022666, 31, 96.796) if diff_forth > 86_400
  end

  # 投稿から5分より長く1時間以下経っていた場合は5分ごとに記憶が落ちるようにするメソッド
  # 引数は左から投稿時間、時間間隔、記憶節約率配列、記憶低減係数、X軸への追加点、Y軸への追加点
  def minute_lost_memory(post_time, diff_time, memory_array, lost_rate, add_x, add_y)
    # 差分の時間を5分で割って5分が何回刻みかを出す
    (diff_time / 300).floor.times do |min_num|
      memory_array.push([post_time.since(((min_num + 1) * 5).minutes),
                         lost_rate * ((min_num + 1) * 5 * 0.016666 - add_x)**2 + add_y])
      # 55分以上経っていた場合は処理を終了させる
      break if min_num == 11
    end
  end

  # 投稿から1時間より長く24時間以下経っていた場合は1時間ごとに記憶が落ちるようにするメソッド
  def hour_lost_memory(post_time, diff_time, memory_array, lost_rate, add_x, add_y)
    # 差分の時間を1時間で割って時間数を出す
    (diff_time / 3600).floor.times do |hour_num|
      memory_array.push([post_time.since(((hour_num + 1)).hours),
                         lost_rate * ((hour_num + 2) - add_x)**2 + add_y])
      # 23時間以上経っていた場合は処理を終了させる
      break if hour_num == 22
    end
  end

  # 投稿から1日より長く1ヶ月以下経っていた場合は1日ごとに記憶が落ちるようにするメソッド
  def day_lost_memory(post_time, diff_time, memory_array, lost_rate, add_x, add_y)
    # 差分の時間を1日で割って日数を出す
    (diff_time / 86_400).floor.times do |day_num|
      memory_array.push([post_time.since(((day_num + 1)).days),
                         lost_rate * ((day_num + 2) - add_x)**2 + add_y])
      # 30日以上経っていた場合は処理を終了させる
      break if day_num == 29
    end
  end

  # 現在のページ数に応じて投稿番号のスタートの戻り値を返すメソッド

app/views/posts/_point_form.html.erb
<p class="post_show_point_check">復習チェックフォーム</p>
<div class="post_show_point_form_box">
  <%# 復習したらチェックして送信するフォーム %>
  <%= form_with(model: post.relearn_points, url: user_post_relearn_point_path(user_id: current_user.id, post_id: post.id), method: :patch, local: true) do |f| %>
  <table class="post_show_point_table">
    <thead class="post_show_point_thead">
      <tr>
        <td><p>CHECK!</p></td>
        <td></td>
        <td><p>ポイント</p></td>
        <td></td>
        <td><p>実施時間</p></td>
        <td><p>通知時間</p></td>
      </tr>
    </thead>
      <%# postテーブルのrelearn_countの値に応じて表示するフォームを変える %>
      <%# 復習回数が0のとき %>
    <tbody class="post_show_point_tbody">
      <tr>
        <td>1回目</td>
        <td><% if plan_timing.first_term <= time_now && post.relearn_count == 0 %>
              <p class="post_show_score_checkbox"><%= f.check_box(:first_score, {checked: false}, checked_value = "true",unchecked_value = "false" ) %></p>
            <% elsif post.relearn_count > 0 %><i class="far fa-check-square"></i>
            <% end %>
        </td>
        <td><%= post.relearn_points[0][:first_score] %> / 100 P</td>
        <td></td>
        <td><%= real_timing.first_term.strftime("%Y-%m-%d %H:%M") unless real_timing.first_term.nil? %></td>
        <td><%= plan_timing.first_term.strftime("%Y-%m-%d %H:%M") %></td>
      </tr>
      <tr>
        <td>2回目</td>
        <td><% if plan_timing.second_term <= time_now && post.relearn_count == 1 %>
              <p class="post_show_score_checkbox"><%= f.check_box(:second_score, {checked: false}, checked_value = "true",unchecked_value = "false" ) %></p>
            <% elsif post.relearn_count > 1 %><i class="far fa-check-square"></i>
            <% end %>
        </td>
        <td><%= post.relearn_points[0][:second_score] %> / 200 P</td>
        <td></td>
        <td><%= real_timing.second_term.strftime("%Y-%m-%d %H:%M") unless real_timing.second_term.nil? %></td>
        <td><%= plan_timing.second_term.strftime("%Y-%m-%d %H:%M") %></td>
      </tr>
      <tr>
        <td>3回目</td>
        <td><% if plan_timing.third_term <= time_now && post.relearn_count == 2 %>
              <p class="post_show_score_checkbox"><%= f.check_box(:third_score, {checked: false}, checked_value = "true",unchecked_value = "false" ) %></p>
            <% elsif post.relearn_count > 2 %><i class="far fa-check-square"></i>
            <% end %>
        </td>
        <td><%= post.relearn_points[0][:third_score] %> / 300 P</td>
        <td></td>
        <td><%= real_timing.third_term.strftime("%Y-%m-%d %H:%M") unless real_timing.third_term.nil? %></td>
        <td><%= plan_timing.third_term.strftime("%Y-%m-%d %H:%M") %></td>
      </tr>
      <tr>
        <td>4回目</td>
        <td><% if plan_timing.forth_term <= time_now && post.relearn_count == 3 %>
              <p class="post_show_score_checkbox"><%= f.check_box(:forth_score, {checked: false}, checked_value = "true",unchecked_value = "false" ) %></p>
            <% elsif post.relearn_count > 3 %><i class="far fa-check-square"></i>
            <% end %>
        </td>
        <td><%= post.relearn_points[0][:forth_score] %> / 400 P</td>
        <td></td>
        <td><%= real_timing.forth_term.strftime("%Y-%m-%d %H:%M") unless real_timing.forth_term.nil? %></td>
        <td><%= plan_timing.forth_term.strftime("%Y-%m-%d %H:%M") %></td>
      </tr>
    </tbody>
    <tfoot class="post_show_point_tfoot">
      <tr>
        <td></td>
        <%# 通知時間前に送信出来ないようにする %>
        <td><% if check_timing_bool(plan_timing, post.relearn_count, time_now) %>
              <%= f.submit "復習登録" ,class:"post_show_score_form_btn"%>
            <% end %></td>
        <td><%= post.relearn_points[0][:first_score] + post.relearn_points[0][:second_score] + post.relearn_points[0][:third_score]+ post.relearn_points[0][:forth_score] %> / 1000 P</td>
        <td></td>
        <td></td>
        <td>
          <%# 4回目の通知時間が現在を過ぎていたら編集できないようにする %>
          <% if plan_timing.forth_term >= time_now %>
            <%= link_to edit_user_post_plan_timing_path(user_id: current_user.id, post_id: post.id) do %><p class="post_show_edit_plan_btn">通知時間の編集</p><% end %>
          <% end %>
        </td>
      </tr>
    </tfoot>
  </table>
  <% end %>
</div>

app/views/posts/show.html.erb
<%# フレンドユーザーの投稿であれば見れるようにする %>
<% if @other_user.id != current_user.id %>
  <h1><%= @other_user.name%>さんの投稿詳細</h1>
  <div class="post_index_friend_btn_box">
    <div class="post_index_friend_posts_btn"><%= link_to user_posts_path(user_id: @other_user.id) do %><p><%= @other_user.name %><br>さんのRelearn 一覧</p><% end %></div>
    <div class="post_index_friend_complete_posts_btn"><%= link_to complete_posts_path(id: @other_user.id) do %><p><%= @other_user.name %><br>さんのRelearn 履歴</p><% end %></div>
  </div>
<% else %>
  <div class="post_show_top_title">
    <h1>投稿詳細</h1>
    <a href="https://twitter.com/intent/tweet?text=【<%= @post.title.truncate(40) %>】を復習します%0a&url=https://re-learn.work/users/<%= @post.user_id %>/posts/<%= @post.id %>/&hashtags=relearn,復習" class="twitter-share-button" data-size="large" data-lang="ja" onClick="window.open(encodeURI(decodeURI(this.href)), 'tweetwindow', 'width=650, height=470, personalbar=0, toolbar=0, scrollbars=1, sizable=1'); return false;" rel="nofollow"><i class="fab fa-twitter fa-2x post_show_twitter"></i>ツイッターで共有する</a>
  </div>
<% end %>
<div class="row">
  <div class="post_show_box">
    <div class="post_show_main_box col-xs-3">
      <div class="post_title_box">
        <p class="post_show_title"><%= @post.title%></p>
        <p class="post_show_genre"><%= @genre.type.truncate(20)%></p>
      </div>
      <div class="content_head">
        <p class="post_show_content_title">内容</p>
        <%# 他のユーザーからは見えないようにする %>
        <% if @other_user.id == current_user.id %>
          <%= link_to edit_user_post_path(user_id: current_user.id, id: @post.id) do %><p class="post_show_content_edit">投稿内容の編集</p><% end %>
        <% end %>
      </div>
      <div class="post_show_content">
        <%= markdown(@post.content).html_safe %>
      </div>
      <%# target="_blank"をつけることでb別タブに飛ばす。rel="noopener noreferrer" %>
      <p class="post_show_link">link : <a href="<%= @post.link %>" target="_blank" rel="noopener noreferrer"><%= @post.link.truncate(70) %></a></p>
    </div>
    <div class="post_show_graph_box col-xs-9">
      <p class="post_show_graph_title"><投稿後の忘却推移></p>
      <%# 記憶忘却推移を表現したグラフ %>
      <%= render partial: "layouts/chart", locals:{ post: @post, height: '400px' } %>
    </div>
  </div>
  <%# 他のユーザーはポイント入力フォーム以下は見えないようにする %>
  <% if @other_user.id == current_user.id %>
    <div class="post_show_bottom_box col-xs-12">
      <%# ポイント入力フォーム %>
      <%= render partial: 'point_form', locals: { post: @post,
            plan_timing: @plan_timing, time_now: @time_now, real_timing: @real_timing } %>
        <p class="post_show_bottom_message">※通知時間になるまでは復習登録は出来ません</p>
          <div class="post_show_bottom_btn">
            <%= link_to relearn_complete_path(@post), method: :patch, data: {confirm: "復習完了にしますか？"} do %><p class="post_show_complete_btn">復習完了にする</p><% end %>
            <%= link_to user_post_path(user_id: current_user.id, id: @post.id), method: :delete, data: {confirm: "投稿を削除しますか？"} do %><p class="post_show_delete_btn">投稿を削除する</p><% end %>
          </div>
    </div>
  <% end %>
</div>