config/routes.rb
Rails.application.routes.draw do
  # WEB上でメールを確認できる。必要なときのみコメントアウトを外す。
  # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env == 'development'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    # このpathを通して外部API認証が行われる。
    :omniauth_callbacks => 'users/omniauth_callbacks'
   }
  root 'homes#top'
  get '/about' => 'homes#about'
  # ジャンルごとの投稿一覧
  get '/posts/genre/:user_id/:id' => 'posts#genre_posts_index', as: 'genre_posts_index'
  # 復習完了した投稿一覧、ユーザーの区別をするためid有りにする
  get '/posts/completes/:user_id' => 'completes#index', as: 'complete_posts'
  # 復習回数が4回未満で復習完了する場合
  patch 'posts/:id/relearn_complete' => 'completes#relearn_complete', as: 'relearn_complete'
  # 全体ポイントランキング表示
  get '/point_rank' => 'ranks#point_rank'
  # 友達ポイントランキング表示
  get '/friend_point_rank' => 'ranks#friend_point_rank'
  # 全体の復習リズムランキング
  get '/rhythm_rank' => 'ranks#rhythm_rank'
  # 友達の復習リズムランキング
  get '/friend_rhythm_rank' => 'ranks#friend_rhythm_rank'
  # 退会確認画面
  get '/sign_out_confirm' => 'users#sign_out_confirmation'
  # 友達検索の画面
  get 'user/:id/friend_search' => 'friends#search', as: "friend_search"
  # 友達リクエスト一覧表示
  get 'user/:id/friend_receive' => 'friends#receive', as: "friend_receive"
  # リクエスト送ったときに使う
  post 'user/:id/send_request' => 'friends#send_request', as: "send_request"
  # リクエスト取り消し
  delete 'user/:id/cancel_request' => 'friends#cancel_request', as: "cancel_request"
  # 通知を全削除
  delete 'user/:id/notification' => 'notifications#destroy_all', as: "destroy_all_notifications"
  resources :users, only: [:edit, :update, :destroy] do
    resources :genres, only: [:index, :create, :update, :destroy]
    resources :notifications, only: [:index]
    resources :friends, only: [:index, :update, :destroy]
    # current_userと友達の投稿を区別する必要があるためネストする
    resources :posts do
      # 通知時間はpost_idが必要
      # plan_timingのidは不要のためresourceを使用
      resource :plan_timing, only: [:edit, :update]
      resource :complete, only: [:show, :update, :destroy]
      # 復習ポイントフォームでの入力値受け取り用
      resource :relearn_point, only: [:update]
    end
  end
end

app/views/layouts/_chart.html.erb
<%# 記憶忘却推移を表現したグラフ %>
<%= area_chart memory_point_array(post),
          id: 'total-attendance-chart',
          width: '100%',
          height: height,
          marigin_top: '30px',
          colors: ['#F99F48'],
          xtitle: "時間経過", ytitle: "節約率",
          xmin:  post.created_at.ago(1.minutes).strftime('%m/%d %H:%M'),
          xmax: post.created_at.since(10.days).strftime('%m/%d %H:%M'),
          min: 0, max: 100,
          points: false, curve: false,
          messages: {empty: "グラフデータがありません"},
          discrete: true
          %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class = "alert alert-danger">
    <ul class="error_message">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<%# 成功・エラー文表示 %>
<% if flash %>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
      <%= message %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_head.html.erb
<head>
  <title>Relearn</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <script src="https://kit.fontawesome.com/9ec8e86bb6.js" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 
  <%= favicon_link_tag('favicon.ico') %>
</head>

app/views/layouts/_header.html.erb
<header>
  <%# ロゴをリンク化 %>
  <%= link_to root_path, class:"logo" do %>
    <%= image_tag "ReLearn-logo-orange.png", class: "logo_img" %>
  <% end %>
  <% if user_signed_in? %>
    <nav class="header_nav">
      <ul class="nav-list_center">
        <%= link_to new_user_post_path(user_id: current_user.id) do %><li class="nav-list-item-center">+新規投稿</li><% end %>
        <%= link_to user_posts_path(user_id: current_user.id) do %><li class="nav-list-item-center">Relearn一覧</li><% end %>
        <%= link_to complete_posts_path(user_id: current_user.id) do%><li class="nav-list-item-center">Relearn履歴</li><% end %>
      </ul>
    </nav>
    <div class="header_right_box">
      <div class="header_right">
        <ul class="nav-list">
          <%# イメージ画像かユーザーの名前を押すとユーザー編集画面にとぶ %>
          <%= link_to edit_user_path(current_user) do %>
            <span id=nav_user_info>
              <%= render partial: "layouts/user_info", locals: { user: current_user} %>
            </span>
          <% end %>
          <%= link_to user_notifications_path(current_user.id) do%> 
            <% if unchecked_notifications.any? %>
              <li class="nav-list-item fa-stack">
                <i class="far fa-bell fa-lg fa-stack-2x"></i>
                <i class="fa fa-circle fa-stack-1x n-circle"></i>
              </li>
            <% else %>
              <li class="nav-list-item"">
                <i class="far fa-bell fa-lg" style="font-size: 1.8em;"></i>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  <% else %>
    <nav class="header_nav">
      <ul class="nav-list_center">
        <%= link_to about_path do %><li class="nav-list-item-center">about</li><% end %>
        <%= link_to new_user_registration_path do %><li class="nav-list-item-center">新規登録</li><% end %>
        <%= link_to new_user_session_path do %><li class="nav-list-item-center">ログイン</li><% end %>
      </ul>
    </nav>
  <% end %>
</header>
<% if user_signed_in? %>
  <%= render "layouts/menu" %>
 <% end %>

app/views/layouts/_menu.html.erb
<div class="under_menu">
  <nav class="header_under_nav">
    <ul class="under_nav-list">
      <%= link_to about_path do %><li class="under_nav-list-item">ReLearnについて</li><% end %>
      <%= link_to edit_user_path(current_user.id) do %><li class="under_nav-list-item">アカウント設定</li><% end %>
      <%= link_to friend_search_path(current_user.id) do %><li class="under_nav-list-item">友達を探そう</li><% end %>
      <%= link_to point_rank_path do %><li class="under_nav-list-item">ランキング</li><% end %>
      <%= link_to destroy_user_session_path, method: :delete, data: { confirm: 'ログアウトしますか？' } do %><li class="under_nav-list-item">ログアウト</li><% end %>
    </ul>
  </nav>
</div>

app/views/layouts/_side_genre.html.erb
<h3 class="side_title">ジャンル一覧</h3>
<div class="side_genre">
  <ul>
    <% genres.each do |genre|%>
      <li><%= link_to genre.type.truncate(18), genre_posts_index_path(user_id: genre.user.id, id: genre.id) %></li>
    <% end %>
  </ul>
  <br>
  <%# 他のユーザーからは見えないようにする %>
  <% if @other_user.id == current_user.id %>
    <%= link_to "ジャンルの追加/編集",  user_genres_path(user_id: current_user.id) %>
  <% end %>
</div>

app/views/layouts/_user_image.html.erb
<%# 非同期でヘッダーの画像を更新するために用意したレンダリング %>
<%# users_controller以外では未定義userの部分は、renderの呼び出し側でcurrent_userを使用してエラー回避 %>
<% if user %>
  <li class="nav-list-item"><p><%= attachment_image_tag(user, :image, :fill, 50, 50, fallback: "default.png", class: "nav_user_image") %><p></li>
<% end %>

app/views/layouts/_user_info.html.erb
<%# 非同期でヘッダーの画像を更新するために用意したレンダリング %>
<%# users_controller以外では未定義userの部分は、renderの呼び出し側でcurrent_userを使用してエラー回避 %>
<% if user %>
  <li class="nav-list-item"><p><%= attachment_image_tag(user, :image, :fill, 50, 50, fallback: "default.png", class: "nav_user_image") %><p></li>
  <li class="nav-list-item"><p><%= user.name %><p></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%# ヘッドをレンダリング %>
  <%= render 'layouts/head' %>
  <body>
    <%# ヘッダーをレンダリング %>
    <%= render 'layouts/header' %>
    <main>
      <div class="container">
        <div id="flash_messages">
          <%# 成功・エラー文があれば表示するレンダリング %>
          <%= render "layouts/flash_messages" %>
        </div>
          <%# 各ビューの読み込み %>
          <%= yield %>
        </div>
      </div>
    </main>
    <footer>
      <p>© 2020 ReLearn</p>
      <%# ロゴをリンク化 %>
      <%= link_to root_path, class:"logo" do %>
        <%= image_tag "ReLearn-logo-white.png", class: "footer_logo_img" %>
      <% end %>
    </footer>
  </body>
</html>